blog/applications/entry/urls.py
#
from django.urls import path
from . import views

app_name = "entry_app"

urlpatterns = [
    path(
        'entries/', 
        views.EntryListView.as_view(),
        name='entry-list',
    ),
    path(
        'entry/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),
]

blog/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ), 
    path(
        'suscription-record', 
        views.SubcriberCreateView.as_view(),
        name='add-suscription',
    ),  
    path(
        'rcontact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ),  
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorites.urls')),
    # urls for ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/applications/home/models.py
from django.db import models
# third party apps
from model_utils.models import TimeStampedModel

# Create your models here.

class Home(TimeStampedModel):

    title = models.CharField(
        'Name', 
        max_length=50
    )
    description = models.TextField()
    about_title = models.CharField(
        'Our Title',
        max_length=50
    )
    about_text = models.TextField()
    contact_email = models.EmailField(
        'contact email',
        blank=True,
        null=True
    )
    phone = models.CharField(
        'Contact telephone', 
        max_length=25
    )

    class Meta:
        verbose_name = 'Principal Page'
        verbose_name_plural = 'Principal Page'

    def __str__(self):
        return self.title

class Subcriber(TimeStampedModel):

    email = models.EmailField()

    class Meta:
        verbose_name = 'subcriber'
        verbose_name_plural = 'subcribers'

    def __str__(self):
        return self.email

class Contact(TimeStampedModel):

    full_name = models.CharField(
        'Names', 
        max_length=60
    )
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return self.email

blog/templates/includes/footer.html
<div class="callout secondary">
    <div class="grid-x align-center">
        <h3 class="cell small-12 large-7">Formulario de Contacto:</h3>
        <form class="cell small-12 large-7" method="POST" action="{% url 'home_app:add-contact' %}">{% csrf_token %}
            <div class="grid-x grid-padding-x">
                <div class="medium-6 cell">
                  <label>Nombres
                    <input type="text" placeholder="nombres..." name='full_name' id="id_full_name">
                  </label>
                </div>
                <div class="medium-6 cell">
                  <label>Correo
                    <input type="text" placeholder="Correo ..."  name='email' id="id_email">
                  </label>
                </div>
                <div class="medium-12 cell">
                    <label>Mensaje
                        <textarea placeholder="Mensaje" name='message' id="id_emesage"></textarea>
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit" class="success button">Enviar</button>
                </div>
            </div>
        </form>
        <p class='cell large-8'>otras formas de contacto: </p>
        <p class='cell large-8'>
          <span class='label warning'>{{ email}}</span>
          <span class='label warning'>{{ phone }}</span>
        </p>
    </div>
</div>

blog/templates/includes/header.html
<header>
    <div class="grid-x grid-margin-x header">
        <div class="cell small-12 medium-4 large-3">
            <a href="#" style="font-size: 20px; color: #0277bd;">
                World of data
            </a>
        </div>
        <div class="cell small-12 medium-4">
            
        </div>
        <div class="cell small-12 large-5">
            <ul class="menu" style="justify-content: flex-end;">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="{% url 'entry_app:entry-list' %}">Blog</a>
                </li>
                <li>
                    <a class="success button">Acceder</a>
                </li>
                
            </ul>
        </div>
    </div>
</header>