blog/applications/entry/urls.py
#
from django.urls import path
from . import views

app_name = "entry_app"

urlpatterns = [
    path(
        'entries/', 
        views.EntryListView.as_view(),
        name='entry-list',
    ),
    path(
        'entry/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),
]

blog/applications/home/urls.py
#
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(),
        name='index',
    ), 
    path(
        'suscription-record', 
        views.SubcriberCreateView.as_view(),
        name='add-suscription',
    ),  
    path(
        'rcontact', 
        views.ContactCreateView.as_view(),
        name='add-contact',
    ),  
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorites.urls')),
    # urls for ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/applications/home/models.py
from django.db import models
# third party apps
from model_utils.models import TimeStampedModel

# Create your models here.

class Home(TimeStampedModel):

    title = models.CharField(
        'Name', 
        max_length=50
    )
    description = models.TextField()
    about_title = models.CharField(
        'Our Title',
        max_length=50
    )
    about_text = models.TextField()
    contact_email = models.EmailField(
        'contact email',
        blank=True,
        null=True
    )
    phone = models.CharField(
        'Contact telephone', 
        max_length=25
    )

    class Meta:
        verbose_name = 'Principal Page'
        verbose_name_plural = 'Principal Page'

    def __str__(self):
        return self.title

class Subcriber(TimeStampedModel):

    email = models.EmailField()

    class Meta:
        verbose_name = 'subcriber'
        verbose_name_plural = 'subcribers'

    def __str__(self):
        return self.email

class Contact(TimeStampedModel):

    full_name = models.CharField(
        'Names', 
        max_length=60
    )
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contact'
        verbose_name_plural = 'Messages'

    def __str__(self):
        return self.email

blog/applications/home/forms.py
from django import forms

from .models import Subcriber, Contact

class SubcriberForm(forms.ModelForm):
    class Meta:
        model = Subcriber
        fields = (
            'email',
        )
        widget = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': ' Email...',
                }
            )
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('__all__')

blog/applications/home/views.py
import datetime
#
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.views.generic import (
    TemplateView,
    CreateView
)

from applications.entry.models import Entry

from .models import Home

from .forms import SubcriberForm, ContactForm


class HomePageView(TemplateView):
    template_name = "home/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)

        context['home'] = Home.objects.latest('created')
        context['cover'] = Entry.objects.entry_cover()
        context['home_entries'] = Entry.objects.home_entries()
        context['recent_entries'] = Entry.objects.recent_entries()
        context['form'] = SubcriberForm
        return context



class SubcriberCreateView(CreateView):
    form_class = SubcriberForm
    success_url = '.'

class ContactCreateView(CreateView):
    form_class = ContactForm
    success_url = '.'

blog/templates/home/base_home.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/home/index.html
<!-- head para PC -->
{% extends "home/base_home.html" %}

{% load static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <!-- primer bloque del home -->
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6">
            <div class="card" style="width: 100%;">
                <img src="{{ cover.image.url }}">
                <div class="card-section">
                    <h4><a href="{% url 'entry_app:entry-detail' pk=cover.id %}">{{ cover.title }}</a></h4>
                    <p>{{ cover.summary|truncatechars:105 }}</p>
                </div>
            </div>
        </div>
        <!-- FIN bloque de blog principal -->

        <!-- bloque de blog principal -->
        <div class="cell small-12 large-6 grid-x grid-margin-x">

            {% for entry in home_entries %}
            <div class="cell small-12 large-6">
                <div class="card" style="width: 100%;">
                    <img src="{{ entry.image.url}}" style="height:120px;">
                    <div class="card-section">
                        <h5>
                            <a href="{% url 'entry_app:entry-detail' entry.id%}">{{ entry.title|truncatechars:42 }}</a>
                        </h5>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de blog principal -->
    </div>
    <!-- FIN del primer bloque home -->

    <!-- segundo bloque pantalla home -->
    <div class="grid-x align-center" style="margin-top: 1em;">
        <div class="cell small-12 large-10 callout secondary">
            <h5>{{home.about_title}}</h5>
            <p>
                {{home.about_text}}
            </p>

            <p>
                <button class="button" data-open="exampleModal2">Suscribirme</button>
            </p>

            <!-- This is the first modal -->
            <div class="reveal" id="exampleModal2" data-reveal style="width: 300px;">
                <p class="lead">Ingresa tu correo</p>
                <form class="grid-x grid-margin-x" method="POST" action="{% url 'home_app:add-suscription'%}">{%
                    csrf_token %}
                    <div class="cell small-12">
                        {{ form.email}}
                    </div>
                    <div class="cell small-12">
                        <button type="submit" class="success button">Suscribirme</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- FIN segundo bloque pantalla home -->


    <!-- tercer bloque home -->
    <div class="grid-x grid-margin-x align-center">
        <h3 class="cell">Articulos Recientes:</h3>

        {% for entry in recent_entries %}
        <div class="cell small-6 large-4">
            <div class="card" style="width: 100%;">
                <img src="{{ entry.image.url}}">
                <div class="card-section">
                    <a href="{% url 'entry_app:entry-detail' entry.id%}">{{ entry.title|truncatechars:42 }}</a>
                    <p>{{ entry.summary|truncatechars:84 }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- FIN tercer bloque -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}