blog/applications/favorites/urls.py
from django.urls import path

from . import views

app_name = "favorites_app"

urlpatterns = [
    path(
        'profil/', 
        views.UserPageView.as_view(),
        name='user-profil',
    ),
    path(
        'add-entry/<pk>/', 
        views.AddFavoritesView.as_view(),
        name='add-favorites',
    ),
    path(
        'delete-favorites/<pk>/', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favorites',
    ),
]

blog/applications/users/urls.py
#
from django.urls import path

from . import views

app_name = "users_app"

urlpatterns = [
    path(
        'register/', 
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'login/', 
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/', 
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/', 
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorites.urls')),
    # urls for ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/applications/favorites/models.py
from django.db import models
from django.conf import settings

from model_utils.models import TimeStampedModel
from .managers import FavoritesManager

from applications.entry.models import Entry

class Favorites(TimeStampedModel):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='user_favorites',
        on_delete=models.CASCADE,
    )
    entry = models.ForeignKey(
        Entry,
        related_name='entry_favorites',
        on_delete=models.CASCADE
    )

    objects = FavoritesManager()

    class Meta:
        unique_together = ('user', 'entry')
        verbose_name = 'Favorite Entry'
        verbose_name_plural = 'Favorites Entries'

    def __str__(self):
        return self.title

blog/applications/favorites/views.py
from django.shortcuts import render
#
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
#
from django.views.generic import (
    View,
    ListView,
    DeleteView
)

from applications.entry.models import Entry

#
from .models import Favorites
# Create your views here.

class UserPageView(LoginRequiredMixin, ListView):
    template_name = "favorites/profil.html"
    context_object_name = 'entries-user'
    login_url = reverse_lazy('users_app:user-login')

    def get_queryset(self):
        return Favorites.objects.entries_user(self.request.user)


class AddFavoritesView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users_app:user-login')

    def post(self, request, *args, **kwargs):
        user = self.request.user
        entry = Entry.objects.get(id=self.kwargs['pk'])

        Favorites.objects.create(
            user=user,
            entry=entry,
        )
        return HttpResponseRedirect(
            reverse(
                'favorites_app:profil'
            )
        )

class FavoritesDeleteView(DeleteView):
    model = Favorites
    success_url = reverse_lazy('favoritos_app:perfil')

blog/templates/favorites/base_favorites.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/favorites/profil.html
<!-- head para PC -->
{% extends "base/base_favorites.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center" style="margin-top: 1em;">
        <!-- bloque de datos de usuario -->
        <div class="cell small-12 large-4">
            <div class="callout">
                <h5>{{ user.full_name }}</h5>
                <p> {{ user.email }} - {{ user.ocupation}} - {{ user.date_birth }}</p>
                <a href="#">Editar Datos</a>
                <p>
                    <a href="{% url 'users_app:user-logout' %}" class="clear botton secondary">
                        Salir
                    </a>
                </p>
            </div>
        </div>
        <!-- FIN bloque de datos de usuario -->


        <!-- bloque de articulos favoritos de usuario -->
        <div class="cell large-8 grid-x grid-margin-x align-center">
            
            {% for entry in entries_user %}                
            <div class="cell small-12">
                <div class="card-favoritos">
                    <img class="card-favoritos-img" src="{{ entry.entry.image.url }}">
                    <div class="card-favoritos-body">
                        <h3 class="card-favoritos-body-titulo">{{ entry.entry.title }}</h3>
                        <p class="card-favoritos-body-text">{{ entry.entry.summary }}</p>
                        <div class="card-favoritos-body-actions">
                            <a class="button warning" href="#">Ver</a>
                            <a class="button alert" href="#">Eliminar</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- FIN bloque de articulos favoritos de usuario -->
    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}