blog/applications/entry/urls.py
#
from django.urls import path
from . import views

app_name = "entry_app"

urlpatterns = [
    path(
        'entries/', 
        views.EntryListView.as_view(),
        name='entry-list',
    ),
    path(
        'entry/<pk>/', 
        views.EntryDetailView.as_view(),
        name='entry-detail',
    ),
]

blog/applications/favorites/urls.py
from django.urls import path

from . import views

app_name = "favorites_app"

urlpatterns = [
    path(
        'profil/', 
        views.UserPageView.as_view(),
        name='user-profil',
    ),
    path(
        'add-entry/<pk>/', 
        views.AddFavoritesView.as_view(),
        name='add-favorites',
    ),
    path(
        'delete-favorites/<pk>/', 
        views.FavoritesDeleteView.as_view(),
        name='delete-favorites',
    ),
]

blog/blog/urls.py
"""
Proyecto Curso Django
"""
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.entry.urls')),
    re_path('', include('applications.favorites.urls')),
    # urls for ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/applications/entry/models.py
from django.db import models
from django.conf import settings
# third party apps
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
from .managers import EntryManager

# Create your models here.
class Category(TimeStampedModel):
    """ Categoria de entrada"""

    short_name = models.CharField(
        'Name', 
        max_length=50
    )
    name = models.CharField(
        'Name', 
        max_length=50
    )

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Tag(TimeStampedModel):

    name = models.CharField(
        'Name', 
        max_length=30
    )

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name

class Entry(TimeStampedModel):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )
    tag = models.ManyToManyField(Tag)
    title = models.CharField(
        'Title', 
        max_length=50
    )
    summary = models.TextField('Summary')
    content = RichTextUploadingField('Content')
    public = models.BooleanField(default=False)
    image = models.ImageField(
        'Image',
        upload_to = 'Entry'
    )
    cover = models.BooleanField(default=False)
    in_home= models.BooleanField(default=False)
    slug = models.SlugField(editable=False, max_length=300)

    objects= EntryManager()
    
    class Meta:
        verbose_name = 'Entry'
        verbose_name_plural = 'Entries'

    def __str__(self):
        return self.title

blog/applications/entry/views.py
from django.shortcuts import render

from django.views.generic import(
    ListView, 
    DetailView,
)

from .models import Entry, Category

# Create your views here.

class EntryListView(ListView):

    template_name = "entry/list.html"
    context_object_name ='entries'
    paginate_by = 10

    
    def get_context_data(self, **kwargs):
        context = super(EntryListView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context
    

    def get_queryset(self):
        kword = self.request.GET.get("kword", '')
        category = self.request.GET.get("category", "")
        # search query
        result = Entry.objects.search_entry(kword, category)
        return result


class EntryDetailView(DetailView):
    model = Entry
    template_name = "entry/detail.html"

blog/templates/entry/base_entry.html
{% extends "base.html" %}

{% load  static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/myblog.css' %}">
{% endblock css %}

{% block js %}

{% endblock js %}

blog/templates/entry/detail.html
<!-- head para PC -->
{% extends "entry/base_entry.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <h3 class="cell">{{ object.title}}</h3>

        <!-- bloque de contenido del articulo -->
        <div class="cell large-8">
            <div class="cell callout primary">
                <h5>Summary:</h5>
                <p>{{ entry.summary }}</p>
            </div>
            <div>
               <p>{{ entry.content|safe}}</p>
            </div>
        </div>
        <!-- FIN bloque contenido del articulo -->

        <!-- bloque llamada a la accion -->
        <div class="cell large-4">
            <div class="card" style="width: 100%;">
                <img src="https://neunapp.com/media/blog/header16.jpg">
                <div class="card-section" style="width: 100%;">
                  <form class="blog-action" action="{% url 'favorites_app:add-favorites' pk=entry.id %}" method='POST'> {% csrf_token %}
                    <button type='submit' class="blog-action">Agregar a Favoritos</button>
                  </form>
                </div>
            </div>
        </div>
        <!-- FIN bloque llamada a la accion -->

    </div>
</div>
{% include "includes/footer.html" %}

{% endblock content %}

blog/templates/entry/list.html
<!-- head para PC -->
{% extends "entry/base_entry.html" %}
{% load  static %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x" style="margin-top: 1em;">
        <!-- primer bloque pantalla blog -->
        <div class="cell small-12 large-8">

            <!-- bloque de buscador -->
            <form class="input-group" method="GET">{% csrf_token %}
                <input class="input-group-field" type="text" id="kword" name="kword" placeholder="Buscar ...">
                <div class="input-group-button">
                  <input type="submit" class="button" value="Buscar">
                </div>
            </form>
            <!-- FIN bloque de formulario -->

            <!-- inicio bloque de resultados de busqueda -->
            <div class="grid-x grid-margin-x">
                
                {% for entry in  entries%}                    
                <div class="cell small-6 large-4">
                    <div class="card" style="width: 100%;">
                        <img src="{{ entry.image.url }}" style="width: 300px;">
                        <div class="card-section">
                          <a href="{% url 'entry_app:entry-detail' entry.id%}">{{ entry.title|truncatechars:42 }}</a>
                          <p>{{ entry.summary | truncatechars:100}}</p>
                        </div>
                    </div>
                </div>
                {% empty %}
                <h3 style='color:red'>no results found</h3>
                {% endfor %}
            </div>
            <!-- FIN bloque de resultados de busqueda -->

        </div>
        <!-- FIN primer bloque pantalla blog -->


        <!-- inicio del segundo bloque - categorias -->
        <div class="cell small-12 large-4" style="height: 500px;">
            <h4>Categorias</h4>
            <ul class="vertical menu">
                
                {% for category in categories %}
                <li><a href="?category={{ categoria.short_name }}">{{ category.name }}</a></li>  
                {% endfor %}
            </ul>
        </div>
        <!-- FIN inicio del segundo bloque - categorias -->
    
    </div>

    <!-- inicio de bloque de paginacion -->
    <div class="cell">
        {% if is_paginated %}
        <nav aria-label="Pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                </li>
                {% endif %}
                
                {% for pagina in paginator.page_range %}

                
                {% ifequal pagina page_obj.number %}
                <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                {% else %}
                <li class=""><a href="?page={{pagina}}">{{ pagina }}</a></li>
                {% endifequal %}
                {% endfor %}
                
                {% if page_obj.has_next %}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
    <!-- FIN bloque de paginacion -->
</div>
{% include "includes/footer.html" %}

{% endblock content %}